name: agoriya
description: Agoriya v1.0 - Field Force Tracking App
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0
  firebase_messaging: ^16.1.3

  # Maps
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Location
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # Background service
  flutter_background_service: ^5.0.9
  flutter_local_notifications: ^18.0.0

  # Camera
  camera: ^0.12.0+1
  image_picker: ^1.1.2

  # Local storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # HTTP (for OSRM)
  http: ^1.2.2
  dio: ^5.7.0

  # Fonts
  google_fonts: ^8.0.2

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4
  image: ^4.2.0
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A6B3C"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  web:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
